### ISSUE TITLE
Default Test Broken

### ISSUE THREAD

**Issue by rcalxrc08** [AcadiaSoft/simm-lib#1]
The following default test are broken:
- testRisk1: 
Expected :73500000
Actual   :131106740
- testIRV4:
Expected :224633128
Actual   :647806952
- testIRV5:
Expected :73500000
Actual   :131106740
- testIRV7:
Expected :410307997
Actual   :834388517
- testIRV8:
Expected :492798022
Actual   :777441687
I am running on IntelliJ IDEA  2017.2.5. SDK 1.8 on Windows

**Comment by asherwin-acadiasoft** [comment]
Hi @rcalxrc08, thanks for the report.

There was an issue when merging the changes from our internal repository to the public one.  Two unit test files didn't have their test cases updated appropriately, but the underlying implementation logic was not affected.

The issue was missed because the default behavior of the `maven-surefire-plugin` inadvertently skipped these tests when run from the command line since the filenames did not end in the default convention based naming of `*Test.java`

Both issues have been mitigated in 174f9a3be119c380588b520ffa73ab62e3d049e3

Thank you
