### ISSUE TITLE
Tenor For Risk_Equity

### ISSUE THREAD

**Issue by haidp** [AcadiaSoft/simm-lib#10]
Dear all,

thanks again for answering my previous question. During testing we encountered the following issue while calculating Delta Margin values of Risk_Equity type:

As stated in the CRIF file description from [ISDA](https://www.isda.org/a/owEDE/risk-data-standards-v1-36-public.pdf) in chapter 2.5, it is stated that Label1 (Tenor) should not have an effect on the outcome for the initial Delta margin (Label1: Unused, blank). 

Using the following examples, we noticed that this is not the case in the implementation. 

|ProductClass|RiskType   |Qualifier    |Bucket|Label1|Label2  |Amount|
|------------|-----------|-------------|------|------|--------|------|
|Equity      |Risk_Equity|TESTQUALIFIER|11    |3y    |TESTCPTY|10    |
|Equity      |Risk_Equity|TESTQUALIFIER|11    |10y   |TESTCPTY|10    |

results in a Delta margin of *284.46*, while 

|ProductClass|RiskType   |Qualifier    |Bucket|Label1|Label2  |Amount|
|------------|-----------|-------------|------|------|--------|------|
|Equity      |Risk_Equity|TESTQUALIFIER|11    |3y    |TESTCPTY|10    |
|Equity      |Risk_Equity|TESTQUALIFIER|11    |3y    |TESTCPTY|10    |

results in a Delta margin of *340.0*. 

I am using the following function call, where `ldc` is a list of CRIF objects of the above data. 

```java
 NoConversionFxRate fx = new NoConversionFxRate();
        ImRole rolePledgor = ImRole.PLEDGOR;
        ImRole roleSecured = ImRole.SECURED;
        SimmCalculationType typeTotal = SimmCalculationType.TOTAL;
        SimmCalculationType typeX = SimmCalculationType.STANDARD;

        // run imp
        SimmpleResult res = Simmple.calculateSimmWorstOf(ldc, "EUR", fx,"EUR", roleSecured, typeX);
```

Any idea why this would be the case?

Thanks,
Philip

**Comment by Alec-Stewart** [comment]
Philip,

First, the issue you are seeing is *technically* because the data you are inputting doesn't follow the spec; SIMM expects that the `label1` field will be blank for equity delta sensitivities (as you noted). That being said, the library should strive to enforce the data spec wherever possible, so let me dive into what exactly is happening here and I will look at providing a fix in the next release.

This issue is coming from how the sensitivities are netted together before any weightings are applied. Simm-lib uses the function `determineRiskFactor()` as the key to group sensitivities that have the same risk factor as per [ISDA](https://www.isda.org/a/osMTE/ISDA-SIMM-v2.2-PUBLIC.pdf) section 7a, 8a, etc. Thus, the `SensitivityIdentifier` object output from this function is supposed to be a one-to-one map for the risk factor of whatever sensitivity it is being called for. Honestly, this function currently just does the bare minimum to meet the spec given correctly formatted data. The problem you are seeing would be fixed by a tweak like the following:

```java
default SensitivityIdentifier determineRiskFactor() {
    String label1 = this.getLabel1();
    String qualifier = this.getQualifier();
    RiskClass riskClass = this.getRiskIdentifier();

    if (this.getSensitivityClass().equals(SensitivityClass.VEGA) || this.getSensitivityClass().equals(SensitivityClass.CURVATURE)) {
      // we need to sum over all of the vol-tenors for certain risk types, thus we specify label1 which holds vega vol-tenor values
      if (RiskClass.EQUITY.equals(riskClass) ||
        RiskClass.FX.equals(riskClass) ||
        RiskClass.COMMODITY.equals(riskClass) ||
        (RiskClass.INTEREST_RATE.equals(riskClass) && this.getRiskType().equals(RiskClass.RISK_TYPE_INFLATION_VOL))) {
        label1 = null;
      }

      // for FX Vega risk, the order of the currency pair is irrelevant, so we order alphabetically
      if (RiskClass.FX.equals(riskClass)) {
        String ccy1 = StringUtils.substring(qualifier, 0, 3);
        String ccy2 = StringUtils.substring(qualifier, 3, 6);
        qualifier = Stream.of(ccy1, ccy2).sorted().reduce("", (s1, s2) -> s1 + s2);
      }
    } else { // Delta
      if (RiskClass.EQUITY.equals(riskClass) {
        // label1 should be unused for equity delta sensitivities so always set it blank
        label1 = null;
      }
    }

    return new DefaultSensitivityIdentifier(null, this.getProductClass(), this.getRiskType(), qualifier,
      this.getBucket(), label1, this.getLabel2(), this.getSensitivityClass(), riskClass);
  }
```

This change would make it so that the `label1` value would be ignored even if there is something set and so your first example and second example would both output *340.00* as expected.

Although, now that I am thinking about it, perhaps a better solution would be to update the `checkSensitivityIdentifier()` function to enforce the data spec, and then simply call it every time a `DefaultSensitivityIdentifier` is built so that the calculation would throw an exception if the input sensitivities don't match what is expected. 

Unfortunately, I wrote this library in Java so the typings are already fairly bloated. I wouldn't want to create a class for each risk-class and sensitivity-class pairing to manage their own risk factor, so `if` statements in the check function is probably the simplest implementation. A future Kotlin port (or really any language with duck-typing) might clean things up and make this more feasible, but that would be a while off.

Anyway, I am going to close this issue for now as I think I have answered your question.
Let me know id you have any further questions.

Alec
