### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by haidp** [AcadiaSoft/simm-lib#7]
Hi, 
I am currently trying to run your implementation to validate results from our own SIMM scripts as a university project. 
Could you please give me advice on how to actually run the application, as in calculating initial margins from a provided crif file.
After the initial compile command (which runs through) i am stuck at getting the application to run.
Thanks!

**Comment by AmitGee** [comment]
This isn't an application but a class lib - you need to call it from your app. Deserialise your CRIF into Sensitivity objects and call the methods on the Simmple class.

**Comment by Alec-Stewart** [comment]
To explain a little more in-depth, the project is Maven based so you will want to get the dependency available locally. Since the code compiles on your machine, simply running `mvn clean install` at the root of the project should do it. You can check that the `install` worked by checking under the hidden `~/.m2` directory (specifically `~/.m2/repository/com/acadiasoft/im/simm-ple`) to see that a directory `2.2.1` is present (assuming you are using the latest version of the code). 

You should now be able reference the library as a dependency in whatever application you are writing by adding the following to your `pom`:
```
<dependency>
    <groupId>com.acadiasoft.im</groupId>
    <artifactId>simm-ple</artifactId>
    <version>2.2.1</version>
</dependency>
```

From there it is exactly as @AmitGee stated. Your application should somehow take in CRIF data and convert it into `Crif` objects that then allow you to make a call to a method on the Simmple class. The [DefaultCrif](https://github.com/AcadiaSoft/simm-lib/blob/master/simm-ple/src/main/java/com/acadiasoft/im/simmple/model/DefaultCrif.java) class provides [Jackson Annotations](https://github.com/FasterXML/jackson-annotations) that would make deserializing CRIF data from a JSON pretty easy. So I would recommend going that way if you can.

I am going to close this issue, but feel free to comment again if you have problems.
