### ISSUE TITLE
Vega Calculation for Equities

### ISSUE THREAD

**Issue by haidp** [AcadiaSoft/simm-lib#8]
Hi all,

I am currently trying to calculate Vega risk for equities (RiskType: RiskEquityVol) using the Simmple.calculateSimmWorstOf function. 

It runs through fine if using ```ImRole rolePledgor = ImRole.PLEDGOR;``` but when using 
```ImRole roleSecured = ImRole.SECURED;``` I run into the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: The currency was either null or not a three character code as was required.
```
Where this is my function call 
```java
SimmpleResult res = Simmple.calculateSimmWorstOf(ldc, "USD", fx, "USD", roleSecured, typeTotal);
```
and ```ldc``` is my list of DefaultCrif objects.

Any idea why this would be the case?
Thanks

**Comment by Alec-Stewart** [comment]
The following is where this error is being thrown from:
https://github.com/AcadiaSoft/simm-lib/blob/37e54dfc45617caa3749cf3cd051283a08c433b9/base/src/main/java/com/acadiasoft/im/base/model/amount/CurrencyAmount.java#L71

If you look at it, this is a check is made when a `DefaultSensitivity` is built:
https://github.com/AcadiaSoft/simm-lib/blob/37e54dfc45617caa3749cf3cd051283a08c433b9/simm/src/main/java/com/acadiasoft/im/simm/model/Sensitivity.java#L71-L78

This occurs because our `DefaultCrif` are converted to `DefaultSensitivity` using the function below:
https://github.com/AcadiaSoft/simm-lib/blob/37e54dfc45617caa3749cf3cd051283a08c433b9/simm-ple/src/main/java/com/acadiasoft/im/simmple/model/Crif.java#L64-L70

You might note that when the role is Secured, the `DefaultCrif` is simply returned as an extending type. This is the source of your error. You need to set the `amount` and `amountCurrency` fields on all of your `DefaultCrif` or else this check will continue to fail. In the future, I can probably change this check to not bother checking those fields if the `amountUsd` field is set, but for now, that is how you would resolve your issue.
